[package]
name = "duels"
version = "1.0.0"

[addresses]
source_address = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"